# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/develop/code/vivado/lab4/lab4.srcs/sources_1/ip/Data_mem/Data_mem.xci
# IP: The module: 'Data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/develop/code/vivado/lab4/lab4.srcs/sources_1/ip/Data_mem/Data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/develop/code/vivado/lab4/lab4.srcs/sources_1/ip/Data_mem/Data_mem.xci
# IP: The module: 'Data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/develop/code/vivado/lab4/lab4.srcs/sources_1/ip/Data_mem/Data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
